### ISSUE TITLE
Timeline not showing all events

### ISSUE THREAD

**Issue by calum-buchanan** [videege/flagship#47] opened 2020-04-28 12:37 UTC
Since the last update I can only see events in the timeline up to a certain point. We're at the end of Act 2 Turn 1, but the Timeline is only showing up to Act 1 Turn 2. 

Believe timeline was working fine up until yesterday so did look at https://github.com/videege/flagship/pull/36 (as that altered the timeline to include objectives) but wasn't able to spot what would have changed this. 

The last event shown is the manual change of a user's XP, and stops at the same point on multiple devices so suspect it's something to do with how it loops through events. Did skim through the contents of flagship/src/app/campaign/event-timeline as that seems the most likely place for this type of thing but couldn't identify where it was happening. 

Timeline cutoff:
![image](https://user-images.githubusercontent.com/31128029/80487800-491bb700-8955-11ea-8744-b3fef81d00c8.png)
Current act/turn
![image](https://user-images.githubusercontent.com/31128029/80487828-5638a600-8955-11ea-8822-805a152cb019.png)

**Comment by videege** [comment] 2020-04-29 02:27
I can't reproduce this.  Are you seeing any errors in the browser console?  I just tested it out and events appear to be generating OK locally and on the deployed version.

**Comment by videege** [comment] 2020-04-29 02:28
Alternatively, if is a display issue, can you give me the URL of your campaign so I can see if its something regarding your campaign's data specifically?

**Comment by calum-buchanan** [comment] 2020-04-29 08:15
Cool, so console shows these two on navigating to the timeline:
![image](https://user-images.githubusercontent.com/31128029/80573794-913fe580-89f8-11ea-98c0-5465c96f2ec4.png)

Clicking through the error gets the following:
[flagship_timeline_error.txt](https://github.com/videege/flagship/files/4550449/flagship_timeline_error.txt)


And the campaign's timeline is at https://flagship.barronsoftware.com/campaigns/5iN1XgVaWasdkGVFY8vc/timeline 


Also had a test campaign that I'd been messing around with stuff in, so fired several events through beyond act 1 turn 2 onto that and clicked through and the timeline on that seems to be suffering the same issue:
https://flagship.barronsoftware.com/campaigns/St90WpYaMehZi9vJ1ES5/timeline
![image](https://user-images.githubusercontent.com/31128029/80574511-e2040e00-89f9-11ea-83a3-b4bcadc930c6.png)

I'll try other devices/browsers later and see if they're both producing the same result

**Comment by calum-buchanan** [comment] 2020-04-30 22:27
After a bit of trial-and-error I've got it running locally and tried to reproduce the error but can get beyond act 1 turn 2 even with manually adjusting the xp for a player so not sure why that's happened with both our live campaign and the test one on the actual site, so will try to have another play on the local copy and see if I can make it break in the same way.

**Comment by videege** [comment] 2020-05-01 04:56
I think I may have a fix for this but my pipelines are broken at the moment.  I need to debug this but hopefully I'll have the fix out soon.

**Comment by videege** [comment] 2020-05-09 04:25
Finally got my build pipe working again.  Please see if the fix has resolved your error.

**Comment by calum-buchanan** [comment] 2020-05-09 16:45
No luck unfortunately, reloaded the page and got the update notification but still cuts off there. 
![image](https://user-images.githubusercontent.com/31128029/81479710-d9db7800-921c-11ea-9ec2-f81dfdf87104.png)

**Comment by ande2965** [comment] 2020-06-27 12:16
I just created a pull request to fix this, as I started seeing it too. It looks like it was caused by a recent change to show the played objective at a location. That will fail as soon as you play a pivotal battle. The pull request checks for that and shows the pivotal battle objective in that case instead of causing the timeline to fail to load.

**Comment by videege** [comment] 2020-07-03 02:30
> I just created a pull request to fix this, as I started seeing it too. It looks like it was caused by a recent change to show the played objective at a location. That will fail as soon as you play a pivotal battle. The pull request checks for that and shows the pivotal battle objective in that case instead of causing the timeline to fail to load.

Thanks!

**Closed** 2020-07-03 02:29 UTC
